#ifndef __BBCAT_BASE_REGISTER__
#define __BBCAT_BASE_REGISTER__

#include "misc.h"

BBC_AUDIOTOOLBOX_START
// source file automatically generated by autotools and cmake
extern bool bbcat_register_bbcat_base();
BBC_AUDIOTOOLBOX_END

#endif
